### ISSUE TITLE
Finding songs on case-sensitive platforms

### ISSUE THREAD

**Issue by mikepurvis** [AlisterT/openjazz#1]
On Mac OS X with a case-sensitive filesystem:

```
$ ../OpenJazz
Could not open file: song0.psm
$ ls *.PSM
BONUS.PSM   SONG0.PSM   SONG13.PSM  SONG2.PSM   SONG7.PSM
BOSS.PSM    SONG1.PSM   SONG14.PSM  SONG3.PSM   SONG8.PSM
ENDLEVEL.PSM    SONG10.PSM  SONG15.PSM  SONG4.PSM   SONG9.PSM
ENDSONG.PSM SONG11.PSM  SONG16.PSM  SONG5.PSM
MENUSNG.PSM SONG12.PSM  SONG17.PSM  SONG6.PSM
```

Given that these files are always coming from a DOS archive, would it make sense to upcase the filenames before attempting to open them? Alternatively, at least including fallback logic which tries this path before giving up?

**Comment by AlisterT** [comment]
Sorry for taking so long to reply. Yes, there should be a fallback (some people have lower-case filenames, some people have upper-case filenames). I've merged in your branch. Thanks!
