### ISSUE TITLE
Latest windows version detected as malware

### ISSUE THREAD

**Issue by commella** [AlisterT/openjazz#103]
Has anyone had problems with the windows x64 executable version 20231028?
According to total virus it contains a malware, is it a false positive?

[https://www.virustotal.com/gui/file/44552d88718e550390d4f47ed153433eefd208e0d57fccf49cf9569dad0d6e38/detection](url)

Thank you.
Best regards.

**Comment by carstene1ns** [comment]
It might be the UPX compression. Most scanners are signature-based, so this might happen when there is specific data that is a lookalike.
I would say it is a false-positive, but you can always use the executable from the latest pre-release: https://github.com/AlisterT/openjazz/releases/tag/continuous

**Comment by commella** [comment]
Great thank you very much.
