### ISSUE TITLE
Windows 11 says OpenJazz.exe is a virus

### ISSUE THREAD

**Issue by polaris911** [AlisterT/openjazz#106]
Microsoft Defender: Threat quarantined
Detected: Hacktook: Win32/AutoKMS!pz

After unzipping the archive, I immediately got an alert that a threat was detected. Windows 11 automatically deleted OpenJazz.exe. Seems like a pretty big issue to me.

**Comment by carstene1ns** [comment]
See #103. Use the pre-release until there is a new one, which does not have UPX compression.
