### ISSUE TITLE
Unable to start OpenJazz Continuous build

### ISSUE THREAD

**Issue by vicokoby** [AlisterT/openjazz#108]
**Issue**

- OpenJazz Continuous build does not start on Windows 10 x64
![OpenJazz](https://github.com/AlisterT/openjazz/assets/9407044/20ea2c35-06f3-4250-a6c3-6360e7ba5ed1)

**Environment**

- Windows 10 Pro x64
- OpenJazz Continuos Pre-release
- Jazz 1.3

**Comment by carstene1ns** [comment]
It looks like the dependency libraries besides SDL2 are missing:
`libgcc_s_seh-1.dll`, `libstdc++-6.dll` and `libwinpthread-1.dll`
Should have tested this, sorry for the inconvenience!

Here is a package of them, pulled from msys2 server: [OJ-libs.zip](https://github.com/AlisterT/openjazz/files/14968778/OJ-libs.zip)
Tested now and OJ runs. Will change the CI script accordingly.

**Comment by carstene1ns** [comment]
Now these libs are part of the release zip.
