### ISSUE TITLE
Web port

### ISSUE THREAD

**Issue by midzer** [AlisterT/openjazz#112]
Hi,

I've ported the game in the browser: https://midzer.de/wasm/jazz/

Relevant changes at https://github.com/midzer/openjazz/tree/emscripten

Have a nice week
midzer

**Comment by carstene1ns** [comment]
Thank you, now the latest code will be available here:
https://openjazz.github.io

**Comment by midzer** [comment]
Great!

I've removed my build and linked your deployment at https://midzer.de/games#jazz-jackrabbit

Also, you could further optimize resulting .wasm binary for performance and file size by using https://github.com/midzer/openjazz/blob/emscripten/funcs.txt and extending build command  with `-sASYNCIFY_IGNORE_INDIRECT -sASYNCIFY_ONLY=@funcs.txt`.

Beware, that according to a bug report, game errors on the "3D demo" level though, so another function has to be added.

**Comment by carstene1ns** [comment]
I tried with the `funcs.txt` and it did not work for me, so wanted to leave that for later...🎱
