### ISSUE TITLE
Holiday Hare 1995 startup.0sc: background images not correctly displayed

### ISSUE THREAD

**Issue by carstene1ns** [AlisterT/openjazz#13]
This could be a bug in the RLE decompression, but interestingly enough only the top has garbage and both images are shifted by an even value.

![20190119-203018](https://user-images.githubusercontent.com/4691314/51431453-4649f680-1c29-11e9-9953-1244e5bee432.png) ![20190119-203024](https://user-images.githubusercontent.com/4691314/51431454-4649f680-1c29-11e9-95eb-2d998aa8b404.png)

**Comment by Darknior** [comment]
I have the same bug on PI
But this game has only the new XMAs level, is it possible to add it to the original game ?

**Comment by carstene1ns** [comment]
Never tried this myself, but I guess you can copy over the episode files and music (because there are hopefully no cross references to other files, besides e.g. the different startup screen)
Problem is just when you have both Holiday Hare 94 and 95, because they share the same episode index.

```console
$ ls *.05* XM*.PSM 
BLOCKS.050  LEVEL0.050  LEVEL1.050  LEVEL2.050  PLANET.051   SPRITES.051  XMAS2.PSM
BLOCKS.051  LEVEL0.051  LEVEL1.051  PLANET.050  SPRITES.050  XM3.PSM      XMAS3.PSM
```

Still, this bug remains, as the original engine loads the file fine.

**Comment by Darknior** [comment]
Yes they use the same index and it will not work if we don't modify the engine to show the two XMas levels.
But maybe it's not hard to modify ?

**Comment by carstene1ns** [comment]
It is not just about modifying OJ, as they have the same file names, so they need to be renamed as well.

**Comment by darkstar252** [comment]
It's ony a suggestion , instead of renaming files, you put put the game data onto <SUBDIR> and load the data from the <SUBDIR>. Similar to quake2 engine on the mission pack, only the difference between is the data loads from specific directory not from parameter , instead
