### ISSUE TITLE
compiler preprocessing error on src/io/flle.cpp

### ISSUE THREAD

**Issue by prg318** [AlisterT/openjazz#15]
```depbase=`echo src/io/file.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"openjazz\" -DPACKAGE_TARNAME=\"openjazz\" -DPACKAGE_VERSION=\"0\" -DPACKAGE_STRING=\"openjazz\ 0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"openjazz\" -DVERSION=\"0\" -I.  -DUSE_MODPLUG -DUSE_SOCKETS -DSCALE -I./src -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL   -Wall -g -O2 -MT src/io/file.o -MD -MP -MF $depbase.Tpo -c -o src/io/file.o src/io/file.cpp &&\
mv -f $depbase.Tpo $depbase.Po
src/io/file.cpp:41:6: error: invalid preprocessing directive #defined; did you mean #define?
     #defined LOWERCASE_FILENAMES
      ^~~~~~~
      define
make: *** [Makefile:794: src/io/file.o] Error 1
```
I changed this #define and it worked, but I didn't get a chance to get look deeper to see how its used.

**Comment by carstene1ns** [comment]
Yes, seems @AlisterT is currently MIA. (https://github.com/AlisterT/openjazz/commit/0da5e9bec7004e35120e1592e06a2abb7fac0f7d#commitcomment-20919965)

**Comment by AlisterT** [comment]
Guilty as charged. I've been meaning to do some OpenJazz stuff for a while, including fixing that typo. As it happens, this weekend is good for me.

**Comment by carstene1ns** [comment]
Glad to see you back!
Btw. I would be happy being added as collaborator for this repository, as I certainly will provide some more patches (and ports) for this great engine.

**Comment by carstene1ns** [comment]
This has been fixed, thanks for the notification! 👍
