### ISSUE TITLE
Makefile probably shouldn't be version controlled

### ISSUE THREAD

**Issue by prg318** [AlisterT/openjazz#16]
Each 'Makefile' in an autotools project should be generated by the ./configure script for the system that it is being compiled for.  The 'Makefile' probably shouldn't be checked into version control (I got a bunch of build errors until I regenerated the 'Makefile' with ./configure script

Awesome port by the way

**Comment by carstene1ns** [comment]
Have a look again at the `Makefile`, it is a hand-written one that suffices for most needs (for example as a starting point when porting to another platform). `configure` will replace this with a generated one, when run. This is mostly boilerplate, but has greater compatibility.

You either use the `Makefile` or you do the "autotools way", i.e. you do not simply run `make` on an autotools project without running `configure` before.

**Comment by Darknior** [comment]
Working perfectly on PI for me.
