### ISSUE TITLE
Issues and Report on Raspberry PI

### ISSUE THREAD

**Issue by Darknior** [AlisterT/openjazz#18]
I made this report because i compile your openjazz on PI, and it is the most updated version over the net i think. It is an excellent platform game, and if i can give it to all the **RETROPIE** users it can be really fantastic.

+ The game is starting fine, all is working, i can try many levels **without any bug**.
+ I can play with keyboard or some different **joystick** too.
+ It star in full screen and **ALT+ENTER** change nothing, it is perfect.
+ P for **PAUSE** working fine too.

- But **STATISTIC** are always shown, i can't hide them with F9
- I can play with joystick, users only use it on PI, but i can't map **ESC** key to move back in menu and quit game, it is a big problem.
- **Music don't loop**, i use the CD game version, and stop at the end of track, really crappy for gamers :(
- The bonus stage has some bugs if i remember fine.

- Impossible to launch **JazzJackRabbit 2** ... i have read maybe it can works ?

Like this is the last version over the net with recent update, will some of your team can help to upgrade it ? I can help with beta testing all you want.
Thanks

**Comment by Darknior** [comment]
I have fix the Music loop problem but we must change the make file, i have made a pull request please : 

https://github.com/AlisterT/openjazz/pull/19

And add the lib to linux : 

`sudo apt-get install libxmp-dev`

**Comment by Darknior** [comment]
An other bug that is not cool, the game saving nothing.
- We can't save settings
- We can't save/load games

**Comment by carstene1ns** [comment]
Hi, thanks for the bug reports. Most things you noticed do not seem to be RPi specific, so I am going to open separate issues for them later after confirming.

About <kbd>Alt</kbd>+<kbd>Enter</kbd>: This can be disabled with defining `FULLSCREEN_ONLY` either in the Makefile or in a RPi specific block in `src/io/gfx/video.h`

About Statistics display and Joystick mapping: I do not remember such things when working with the code on other platforms, need to check.

About bonus stages: They are not fully implemented yet (as a lot of other things, too)

About JJ2R level support: http://www.alister.eu/jazz/oj/posts/25
>  I'm not planning any further support for Jazz Jackrabbit 2, nor any kind of support for Jazz Jackrabbit 3D. If you want more features in JJ2, I recommend JJ2+ (http://www.jazz2online.com/jj2plus).

About saving settings: I also had some problems with settings not persisting, but did not tinker with that binary format yet. IMO it would be better to use INI-style plain text configuration.

Good thing you figured out how to make the music loop already, so this will be done when merging the PR. Actually reading `README` files may help in such cases (as mentioned here: https://github.com/zerojay/RetroPie-Extra/issues/262#issuecomment-349857096 😄).

**Comment by Darknior** [comment]
> About Statistics display and Joystick mapping: I do not remember such things when working with the code on other platforms, need to check.

- The DEBUG info only show on 320x200, in 640x480 i have some video glitch on top of the screen but debug is not show.
- On Joystick the problem was we can't map ESC key to navigate on menu and quit game.

For JJ2R i have found an other project, i think it will be better to use it :)
https://www.jazz2online.com/jcf/showthread.php?t=20089

> IMO it would be better to use INI-style plain text configuration.

Yes if possible it will be easy to use.

**Comment by carstene1ns** [comment]
Going to close this one, as the remaining issues are open separately: #26 & #51.
