### ISSUE TITLE
Warnings from clang

### ISSUE THREAD

**Issue by mikepurvis** [AlisterT/openjazz#2]
Lots of each of these:

```
warning: conversion from string literal to 'char *' is deprecated
warning: unused function 'scaleNN_N_def_whole'
warning: delete called on 'X' that is abstract but has non-virtual destructor
warning: private field 'targetLaps' is not used
warning: conversion from string literal to 'char *' is deprecated
```

Not sure if there's interest in cleaning these up, but it would be nice to have a clean build on OS X.

**Comment by AlisterT** [comment]
I try to keep the code warning-free, but different compilers (and different versions of the same compiler) have different warnings enabled by default.
