### ISSUE TITLE
Level music not looping

### ISSUE THREAD

**Issue by Phitherek** [AlisterT/openjazz#20]
When using original version of Jazz Jackrabbit from GOG.com, music in levels is not looping as it should.

Further info: tested on Arch Linux with the latest libraries and OpenJazz version from AUR.

**Comment by Darknior** [comment]
Strange ...
On this project it's not a game problem, it's a library issue.

**Comment by carstene1ns** [comment]
Hi, thanks for the bug report. I guess, I should just enable XMP in my AUR package then… 😀

**Comment by carstene1ns** [comment]
Fixed with the new release (merged the `modplug-loop` branch).
