### ISSUE TITLE
Bonus level end screen jazz head graphics garbage

### ISSUE THREAD

**Issue by Pickle** [AlisterT/openjazz#23]
The animated head of jazz at the end of the bonus level does not render cleanly. Meaning the previous frames are not cleared when the next frame begins so all the previous frames are still visible.
A similar issue was occurring with the intro video some time ago, but with the latest source this is now fixed. Maybe there is some commonality and the fix can be applied to the bonus screen.
Its also worth noting im running on an ARM device, so it may not occur on x86 desktop builds.

**Comment by carstene1ns** [comment]
Confirmed, playback of `BONUS.0SC` is broken currently.

**Comment by Calinou** [comment]
> Meaning the previous frames are not cleared when the next frame begins so all the previous frames are still visible.

I can reproduce that part on commit https://github.com/AlisterT/openjazz/commit/b8bb91495631078fb795ec627bb6286b1041158c (Linux), even on the standard "Level clear!" animation. You can see some of the gun's smoke from old frames even though you shouldn't.
