### ISSUE TITLE
controller sending weird outputs. 

### ISSUE THREAD

**Issue by Nilot352** [AlisterT/openjazz#24]
I have a logitech f710 controller and it is not mapping the analog stick correctly in the down left and right directions and when i start the game it somehow emulates keyboard outputs such as P for pause in the right direction and alt+f4 in the up direction.

I have the latest version of openJazz downloaded from your website.

**Comment by StrikerMan780** [comment]
Same. If I try to use a gamepad, the game randomly quits the level, or other crazy stuff.
