### ISSUE TITLE
Music doesn't speed up when getting running shoes.

### ISSUE THREAD

**Issue by StrikerMan780** [AlisterT/openjazz#25]
It seems the running shoes powerup doesn't speed up the music like it does in the original game. Hopefully this can/will be fixed.

**Comment by carstene1ns** [comment]
I have added that feature, but is currently only supported by a specific music library (`libopenmpt`).

Other missing stuff related to running shoes:
- blue flash is missing
- jazz sprite gets duplicated only once, in original game up to 3 times
