### ISSUE TITLE
port to SDL2?

### ISSUE THREAD

**Issue by fabiangreffrath** [AlisterT/openjazz#33]
Hi there,

is there any chance (or ongoing effort) of porting this game to SDL2? This would make it significantly easier to scale the framebuffer to screen, i.e. the 2x pixel doubling code could get removed.

 - Fabian

**Comment by KranKRival** [comment]
OpenJazzNX - i have ported OpenJazz to SDL2 and Nintendo switch , Sauce Soon ...
https://youtu.be/2AI8i5xkAIU

**Comment by KranKRival** [comment]
https://github.com/KranKRival/OpenJazzNX

**Comment by fabiangreffrath** [comment]
Hm, looks like a single-commit code drop to me. Well, probably better than nothing, thanks!
