### ISSUE TITLE
Do not loop the firing animation without rapid fire upgrades

### ISSUE THREAD

**Issue by xTibor** [AlisterT/openjazz#36]
The firing animation shouldn't loop when having no rapid fire upgrades and holding the fire button.

**Comment by carstene1ns** [comment]
Thank you for your opened issues! Is really appreciated.
I know this is just about the visual thing, but I have a question about rapid fire generally:
How behaves the blaster? In OJ rapid fire does not wear off for it and the counter shows `∞` from the start, but is not available.

**Comment by xTibor** [comment]
> In OJ rapid fire does not wear off for it and the counter shows ∞ from the start, but is not available.
Yep, this is the good behavior. The rapid fire upgrades shouldn't wear off until the player dies. It should even carry over between the levels. The infinite sign on that counter only shows that the blaster has infinite ammo, has no connection with the fire upgrades.
