### ISSUE TITLE
Incorrect fire shield rendering

### ISSUE THREAD

**Issue by xTibor** [AlisterT/openjazz#41]
When the fire shield has three gems left, the gems should be rendered 120 degrees apart, not 90.

**Screenshot:**
![4hitshield](https://user-images.githubusercontent.com/1627292/41645478-6fab872e-7471-11e8-82e8-5a1c36507adf.png)
(Jazz / OpenJazz)

**Comment by carstene1ns** [comment]
Ah, cool, at least this is easy to change :)
