### ISSUE TITLE
Can't change weapons with number keys

### ISSUE THREAD

**Issue by happygreenfrog** [AlisterT/openjazz#46]
In the original version of Jazz Jackrabbit 1, it was possible to change weapons using the number keys, similarly to Jazz Jackrabbit 2. In OpenJazz, this is not the case, you can only cycle through them using the weapon cycling key.

**Comment by carstene1ns** [comment]
I have a preliminary patch for this, however, it seems not to work correctly... https://paste.xinu.at/i6R/

**Comment by fabiangreffrath** [comment]
What exactly is not working correctly?

**Comment by carstene1ns** [comment]
Well, I tried to do the same "fallback logic" the original game does. However, this totally messes up the order.
