### ISSUE TITLE
Scaling without texture filertering

### ISSUE THREAD

**Issue by S0G047** [AlisterT/openjazz#60]
Is there a way to scale up the video without using texture filtering?

**Comment by carstene1ns** [comment]
You mean like on the left? (both are upscaled 3x, right has scale3x applied)
![scal3](https://user-images.githubusercontent.com/4691314/56499228-bbb5b380-6505-11e9-9bfb-ef9ab97385fc.png)

Currently, that is not possible. Do you have a use-case for it?

**Comment by Adam-M93** [comment]
To add to this, I personally really don't like those kinds of filters and prefer nearest neighbour scaling like the left image, I'd definitely like either in game scaler options or even separate release options without the scaler. 
The readme does mention scaling under build options but I don't really know how to build myself.
I'm assuming that not enabling the scaler when building would mean NN would be used instead anyway

**Comment by JackingIntoOnline666** [comment]
I can only join Adam and only made this acc to say: This texture filtering is fucking NASTY
Please make it so I can turn it off, it's eye cancer.

**Comment by lukas-valenta** [comment]
Hello, i just tried out OpenJazz and also found the scaling kinda horrible. I'd be willing to make a PR for this, possibly by adding more options than 2x, 3x, 4x to the menu. For example, i'd do 2x, Scale2x.. in the future, others may be added, like AdvMAME2x, hq2x etc.

**Comment by carstene1ns** [comment]
Closing in favor of #78.
