### ISSUE TITLE
Can you please help me with SDL1.x to SDL2 transition? (palette problems)

### ISSUE THREAD

**Issue by vanfanel** [AlisterT/openjazz#63]
Hi there, @carstene1ns 

I have seen you are an experimented porter and, in fact, you seem to be also in charge of further OJ development.
I have (more or less) made some steps towars porting OJ from SDL1.x to SDL2, but I cant, for the love of me, figure out how to properly manage the palette changes OJ expects to do.

This is how I currently try to implement this:

1) I set up an 8bpp paletted surface so the game puts its frames there, as if it was SDL1.x, called "screen":

https://github.com/vanfanel/openjazz/blob/65116f4254708821861100af1795973933007267/src/io/gfx/video.cpp#L210

2) Then I use an auxiliary RGBA8888 surface, to which I will dump converted pixels from 8bit paletted mode on the screen surface. I also use an RGBA8888 texture for the rendering:

https://github.com/vanfanel/openjazz/blob/65116f4254708821861100af1795973933007267/src/io/gfx/video.cpp#L212

3) Then, this is how I manually convert from 8bpp palette indexes on the "screen" surface to RGBA8888 on the auxiliary surface:
https://github.com/vanfanel/openjazz/blob/65116f4254708821861100af1795973933007267/src/io/gfx/video.cpp#L613

As far as I understand, conversion is well done and, in fact, I have verified the `unit32_t RGBColor` variable contains the right "reconstruction" of bytes formed from the three 8bit r, g and b values.

However, colors are WAY incorrect, as if palette was not right set on the origin 8bpp surface...
Can you please build or take a look at my code? I would like to finish the SDL2 port, but there seems to be something on the game logic that escapes me...

Thanks!

**Comment by vanfanel** [comment]
I have updated my code, I was setting the palette on the screen surface instead of the passed surface in  Video::restoreSurfacePalette():

https://github.com/vanfanel/openjazz/blob/5d8e106569ee0609500f25a9eff25b9364a999e5/src/io/gfx/video.cpp#L358

But I am still getting wrong colors, now black & while foregrounds with correct backgrounds :(

**Comment by carstene1ns** [comment]
Sorry for the late reply, low on free time these days. I like the SDL2 stuff not too invasive, so we can keep compatibility with some older platforms. 

The problem with palette conversion I had before is the [logical palette](http://sdl.beuc.net/sdl.wiki/SDL_SetPalette) (which is grayscale in OJ). We currently need this for some effects to work correctly.
Others have tried this before, but the palette stuff was a blocker:
- https://github.com/Chemrat/openjazz/tree/sdl2
- https://github.com/MaddTheSane/openjazz/tree/sdl2
- https://github.com/sergiou87/openjazz/tree/port-to-sdl2

(btw. #33 is also a thing)

**Comment by vanfanel** [comment]
Dont worry about the late reply, it is a hobby after all.

I am surprised to see that other people tried to port to SDL2 and failed on the same point...
So, any ideas on what could we do about it? The very concept of "logical palette" sounds strange to me: 8bit paletted modes just have pixel values that point to a palette, and I dont understand anything more about it.
So, maybe we should somehow operate both palettes in video::expose() before calling SDL2 SetPaletteColors()? How?

**Comment by KranKRival** [comment]
OpenJazzNX - i have ported OpenJazz to SDL2 and Nintendo switch , Sauce Soon ...
https://youtu.be/2AI8i5xkAIU

**Comment by KranKRival** [comment]
https://github.com/KranKRival/OpenJazzNX

**Comment by swingflip** [comment]
@vanfanel FWIW I cross referenced KranKRival's work and added it to a fork of the latest SC of OpenJazz and have it running fine with SDL2 without the Nintendo Switch specifics. 

Whilst it's 80% clean, it does have the same issue with the bonus levels which are removed on this build as the libNX build. I can do a PR but It wouldn't be wise unless they created a new SDL2 branch upstream. 

(huge thanks to KranKRival of course)

**Comment by vanfanel** [comment]
@swingflip Great! Now if a new SDL2 branch could be created upstream... SDL1.x is not recommended at all in 2020.

**Comment by swingflip** [comment]
I think @carstene1ns is the latest active member, hopefully he reads this and creates a SDL2 branch which we can push a PR to and hopefully fix up.

**Comment by KranKRival** [comment]
oh lets hope so indeed

**Comment by vanfanel** [comment]
@carstene1ns Could you please create the SDL2 branch? This wonderful engine really needs to go SDL2.

**Comment by carstene1ns** [comment]
I am not going to push this in the current state. It is full of bad palette hacks, so needs serious cleanup.
I do not have the time currently to work on this, so nothing is going to happen soon.
