### ISSUE TITLE
Blank window on macOS (installed via homebrew)

### ISSUE THREAD

**Issue by aaronk6** [AlisterT/openjazz#64]
Hi,

First of all, this project is amazing. Thank you so much for keeping Jazz Jackrabbit alive! ❤️

I have an issue playing it on macOS though. I’ve installed OpenJazz on macOS Mojave using homebrew:

```
$ brew installl openjazz
==> Installing dependencies for openjazz: libmodplug and sdl
==> Installing openjazz dependency: libmodplug
==> Downloading https://homebrew.bintray.com/bottles/libmodplug-0.8.9.0.mojave.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring libmodplug-0.8.9.0.mojave.bottle.1.tar.gz
🍺  /usr/local/Cellar/libmodplug/0.8.9.0: 15 files, 342.3KB
==> Installing openjazz dependency: sdl
==> Downloading https://homebrew.bintray.com/bottles/sdl-1.2.15_1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/28/28bfde74acbd1e68c0c2600d0bef4ebe7baf089f62f957779deb2c5dc0df2dd9?__gda__=exp=1562272836~hmac=81272c279caa9410b8a8cc7b65fa7619cccf85bbc74fe186d
######################################################################## 100.0%
==> Pouring sdl-1.2.15_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/sdl/1.2.15_1: 225 files, 1.4MB
==> Installing openjazz
==> Downloading https://homebrew.bintray.com/bottles/openjazz-20180522.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c0/c0f7a1ea63036f0fe37ddc60e4d161fadc549ef84de52ee1ec88c3c00516608f?__gda__=exp=1562272839~hmac=6247fe727f54ecce775d7bb129482c40b8ec9b6c981e76144
######################################################################## 100.0%
==> Pouring openjazz-20180522.mojave.bottle.tar.gz
==> Caveats
The shareware version of Jazz Jackrabbit has been installed.
You can install the full version by copying the game files to:
  /usr/local/opt/openjazz/share/openjazz
==> Summary
🍺  /usr/local/Cellar/openjazz/20180522: 87 files, 3.5MB
```

When running it, I see a blank window:

![Screen Shot 2019-07-04 at 22 40 58](https://user-images.githubusercontent.com/446063/60687117-d369ca80-9eac-11e9-9885-7329f3aca845.png)

It’s worth noting that the audio works and it also reacts to keyboard input. So I can actually control it blindly and start playing.

Any idea what’s causing this?

Thanks!

**Comment by carstene1ns** [comment]
Sorry, no idea. Might be an SDL or driver issue, but I have no way to test this.
I would try toggling full screen, clearing the configuration file, actually building the engine (you are using a binary package) and running from a terminal, but it might not change anything.

**Comment by MaddTheSane** [comment]
SDL 1.2 has issues on more recent versions of Mac OS X. Those issues are not likely to be fixed, and the developers of SDL are urging people to move to SDL2.

**Comment by MurphyMc** [comment]
An SDL 1.2 commit by Sam Lantinga on 2020-04-05 probably fixed this.  I think you should be able to pick it up by installing the SDL formula with `brew install sdl --HEAD`.

**Comment by jhusak** [comment]
brew upgrade sdl fixed my problem (empty window in some compiled applications).
brew install sdl --HEAD lead to missing resources.

**Comment by aaronk6** [comment]
Same here 🥳 Working out-of-the-box now, even on macOS Big Sur.

<img width="436" alt="Screen Shot 2020-11-14 at 12 12 06" src="https://user-images.githubusercontent.com/446063/99145871-afa6bf00-2672-11eb-8155-9bd77cd97cf9.png">

One big caveat is that it won’t scale when resizing the window. Instead, it will increase the canvas size. But I guess that should be a separate bug report, so I’m going to resolve this one.

![Screen Shot 2020-11-14 at 12 13 32](https://user-images.githubusercontent.com/446063/99145919-4d9a8980-2673-11eb-85be-51b5555428d2.jpg)

Certainly interesting to see so much from that level at a glance, but it’s obviously unusable (also because it’s very slow at that window size).

**Comment by MurphyMc** [comment]
Yup; updated homebrew formula for SDL includes the patch.  🎉
