### ISSUE TITLE
release overdue?

### ISSUE THREAD

**Issue by fabiangreffrath** [AlisterT/openjazz#67]
Hi,

the repository is static since May 05 2019, the latest release is from Jan 06 2019. There have been 36 commits since then, maybe it would be good to push out a new release soon?

 - Fabian

**Comment by necros2k7** [comment]
Appveyor nightly build will solve it forever

**Comment by fabiangreffrath** [comment]
First, currently there are no daily builds or any other CI whatsoever set up. Second, I am not interested in Windows binaries, but in actual release tarballs for use in Linux distributions.

**Comment by necros2k7** [comment]
linux builds will be fine at least

**Comment by fabiangreffrath** [comment]
Another 14 months later, any attempts to publish the current code base?

**Comment by alternistom** [comment]
Still nothing?

**Comment by carstene1ns** [comment]
https://github.com/AlisterT/openjazz/releases/tag/20231028 🚀

**Comment by Davi-Morais** [comment]
👏👏👏👏
