### ISSUE TITLE
Key left & up on keyboards lock everwhere during OpenJazz running

### ISSUE THREAD

**Issue by AlexandreCastaing** [AlisterT/openjazz#70]
Key left & up on keyboards are lock everwhere (menu, game...)
I Think all keys of the keyboard are "on" and we can't change the state for all keys.
But we can interact with the game by pressing other keys.
I notice the problem on Linux/Ubuntu (xubuntu). 
I don't know yet what the problem comes from.

**Comment by carstene1ns** [comment]
Try deleting the `openjazz.cfg` file and then reconfigure the controls.

**Comment by AlexandreCastaing** [comment]
I have deleted the openjazz.cfg, I have the same problem.
Also I have an error "Erreur de segmentation (core dumped)".

_I have do the "make" command.
My command to run the game is "./OpenJazz ./cd"_

**Comment by AlexandreCastaing** [comment]
Hi, I have add a condition on the code. The var "enable_JoyAxisMotion" on controls.h defined on 0 disable the mouse axis. 1 = enable the mouse axis.
I defined enable_JoyAxisMotion with 0 by default.

**Comment by carstene1ns** [comment]
So your mouse sends SDL joystick axis events? That is not really an OJ issue then.

**Comment by carstene1ns** [comment]
Closing as this is not a general issue.
