### ISSUE TITLE
Support for xinput devices like the Xbox One gamepad

### ISSUE THREAD

**Issue by Gagert** [AlisterT/openjazz#77]
I can somewhat bind the keys to my wireless Xbox One gamepad, but the directional keys aren't functional at all. I believe SDL2 has libraries for more modern gamepads thereby directional keys, I assume this project uses SDL 1.2 because that's a requirement when manually building the latest build of OpenJazz according to the readme file on the main GitHub page of this project.

When rebinding keys with my Xbox One gamepad, there's no reaction whatsoever while pressing the d-pad on my Xbox One gamepad, just barely touching the right analogue stick however makes the remapping menu map almost all the actions to the given button direction faster than I can react. I'm using Windows 10 64 bit.

Edit: I'm using the old released 64 bit build for Windows 10 64 it as of now, as I haven't been able to successfully compile the newest release of OpenJazz. It looks like the d-pad issue might have been solved according to [this](https://github.com/AlisterT/openjazz/commit/7d0295ea91baa8290ac3f74b4382691a9ee47da4), but since I as of now can't test the latest build, I can't confirm that this is now working in my case. Besides, the issue with button mapping happening too fast may still be an issue even though I'm on an older build.

**Comment by carstene1ns** [comment]
This really looks related to SDL1.2, however, I can use my pad just fine. I have been using it under Linux with xpad driver, though.

**Comment by Gagert** [comment]
I just tested out the newer build you provided me now, and OpenJazz seems to be working decently when mapping to an Xbox One gamepad now.
