### ISSUE TITLE
Enabling & disabling scaling, having that option in the menu, how to disable Scale2x?

### ISSUE THREAD

**Issue by Gagert** [AlisterT/openjazz#78]
I'm personally not that big of a fan of the Scale2x scaling method, I prefer sharp, blocky pixels. However, after reading both the readme file on the GitHub front page of this project, and even the "OpenJazz Manual.txt" that's included with the 20190106 release for win64, the only info I've gather in regards of scaling is the following under the Other Options section in the GitHub readme:

 "SCALE - enable scaling of the video output (i.e. Scale2X...)".

How do I disable Scale2x, what are the alternatives, is there a Normal function under Scaling that I can activate? It would be nice with a more easy to use description here on how to change scaling methods in my opinion (maybe a couple of examples). Even better, could we maybe get a menu entry in regards to scaling methods, making it all easier for the end user to change scaling algorithms?

I prefer this game running in fullscreen with my monitors native resolution (1920x1080), with the game image scaled at 3X normal scaling (blocky pixels), thereby making this looking comparable to the newly released Zool Redimensioned on Steam.

Edit: This issue is closely tied to [this one](https://github.com/AlisterT/openjazz/issues/60) it seems, looks like I'm not the only one disliking the reapplied scaling method that's in this release of OpenJazz.

**Comment by carstene1ns** [comment]
I have a local branch for that, however it is a bit hacky currently. Also the settings system should get a rewrite before.
