### ISSUE TITLE
Add-on Support: [EASY :)]]

### ISSUE THREAD

**Issue by wcapes** [AlisterT/openjazz#84]
Hi

Can we have game add-on support

If we could put additional games in subfolders, like new levels or new campaigns

Would be pretty easy: OPENJAZZ <Folder>   eg: OPENJAZZ LevelPack

This would then load from 'LevelPack' first and if there is no file in 'LevelPack' load the original game files.

so, main game files and openjazz.exe in the main folder, and subfolders for additions ( new music, levels, full games etc etc )
I'll be happy to help if this is accepted

**Comment by carstene1ns** [comment]
This is already possible. It works like you described it.
