### ISSUE TITLE
Jazz disappears when moving

### ISSUE THREAD

**Issue by mdebusk** [AlisterT/openjazz#89]
Jazz disappears here whenever he runs and jumps. I've tried several resolutions and scaling levels and it doesn't seem to change anything. He's there if he's casually strolling, but as soon as he speeds up he disappears.

- Ubuntu 20.04.4
- Kernel 5.4.0-113-generic
- NVIDIA 390.191 driver
- 1920x1080 resolution
- NVIDIA GeForce GTX 660M graphics card

**Comment by carstene1ns** [comment]
Can you check which version of SDL you are using? I had the same problem when using the 'sdl12-compat' library. Arch ships this nowadays, maybe Ubuntu does it too.

**Comment by mdebusk** [comment]
Does this help?

`1dpkg -l | grep sdl | cut -d " " -f 3`:
libsdl-image1.2:amd64
libsdl-mixer1.2:amd64
libsdl-net1.2:amd64
libsdl-sound1.2:amd64
libsdl-ttf2.0-0:amd64
libsdl1.2debian:amd64
libsdl2-2.0-0:amd64
libsdl2-dev:amd64
libsdl2-image-2.0-0:amd64
libsdl2-image-dev:amd64
libsdl2-mixer-2.0-0:amd64
libsdl2-mixer-dev:amd64
libsdl2-net-2.0-0:amd64
libsdl2-ttf-2.0-0:amd64
libsdl2-ttf-dev:amd64

**Comment by carstene1ns** [comment]
`apt-cache show libsdl1.2debian` should give the needed info.
Did you build OJ yourself? Or is it from elsewhere?

**Comment by mdebusk** [comment]
It's the package that shiped in the Ubuntu 20.04 repos.

**Comment by carstene1ns** [comment]
How do you launch OJ? Do you specify multiple game paths?

I can reproduce if I use both Holiday Hare and the Shareware as game folders.
Looks like OJ tries to load graphics from HH, while playing Shareware, which are empty there.

**Comment by mdebusk** [comment]
I run it from a launcher pointing at a directory copied form my old DOS install. It's the registered version, and I have no idea if the shareware levels are in the same folder. It's been... good grief... I have no idea how long it's been. I may have been introduced to the game via a BBS.

The menu shows episodes 1-6, a-c, x, bonus stage, and specific level. Does that tell you if I have the shareware episodes installed? If so, could you tell me which files I have to pack away?

**Comment by mdebusk** [comment]
I just tried it in DosBox (never did it before) and the same thing happens. Also, it DOES NOT happen in the holiday levels, which I'd also never tried playing before under Linux.

**Comment by carstene1ns** [comment]
> I just tried it in DosBox (never did it before) and the same thing happens.
Is this now good or bad? 😄

**Comment by mdebusk** [comment]
Well, it certainly means it's a problem not restricted to openjazz.

**Comment by carstene1ns** [comment]
As said, it happens because the animation blocks are empty in some files (since they are unneeded in Shareware/Holiday Hare). There is currently no way to resolve this without restoring the original file(s). The original engine seems to also load the empty blocks.
