### ISSUE TITLE
How to use "other options"?

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [AlisterT/openjazz#90]
DATAPATH
HOMEDIR
SCALE
FULLSCREEN_ONLY

Are these runtime options, or build? What's the syntax? Nothing I have tried has worked:

(/path/to/cfg is *where I want the cfg to be saved* and /path/to/.EXE is where **JAZZ.EXE** already exists.)

    ./OpenJazz DATAPATH /path/to/cfg /path/to/.EXE

    ./OpenJazz DATAPATH=/path/to/cfg /path/to/.EXE

    ./OpenJazz HOMEDIR /path/to/.EXE

    make DATAPATH /path/to/cfg

    make DATAPATH=/path/to/cfg

    DATAPATH=/path/to/cfg make

...in all cases, `openjazz.cfg` and `openjazz.log` are saved to cwd (current working directory), even when I used `HOMEDIR` it was still saved to cwd and not `~`.

What am I misunderstanding?

(I'm using RetroPie / Debian Linux)

**Comment by carstene1ns** [comment]
All of them are build options. `DATAPATH` and `HOMEDIR` only affect the loading of game files, they are not used for configuration or config.

I want to revamp the file loading, so that your usecase works, but the branch is unfinished yet. (See also issue #53) For the time being I would recommend a simple wrapper script, that changes to the dedicated directory and then launches with options.

**Comment by s1eve-mcdichae1** [comment]
Okay thanks. So to start it I've got a script that changes directory to where I want the config to be, then calls the executable from where it's installed to, and passes the path to where I have the game data:

    cd "/path/to/config/dir"

    "/path/to/OpenJazz" "/path/to/gamedata/dir"

This loads the game in a tiny window on my screen. After adjusting the "resolution" and "scale" it fits the screen better, but I still get a mouse-pointer in the top corner. I thought maybe `FULLSCREEN_ONLY` would solve this but I still can't figure out how to activate it.

You say they are build options. Do I need to do something with the Makefile, or can I just pass command-line args (how?)

I don't know what I'm doing; I tried to do something anyway, it didn't work:

`make FULLSCREEN_ONLY` said `make: *** No rule to make target 'FULLSCREEN_ONLY'. Stop.`

I tried again with `make FULLSCREEN_ONLY=1` which at least did build, but I don't see any difference in result. I also tried with `=true` and `=On`, to no effect.

And how would I use the `SCALE` option? And would that *force* a particular scale, or just default to it?

**Comment by fabiangreffrath** [comment]
Could you try `make CFLAGS="-DFULLSCREEN_ONLY"`?

**Comment by s1eve-mcdichae1** [comment]
@fabiangreffrath well, that did compile, but the file it produced was identical to the one produced with simply `make`, and the mouse pointer is still visible.

That's okay though because I see now (`./OpenJazz -h`) that there *is* a runtime option for (-f)ullscreen, so I can just add that to my launch command. No more mouse pointer here!

**Comment by carstene1ns** [comment]
Kind of XY problem here. 🙂

**Comment by s1eve-mcdichae1** [comment]
> Kind of XY problem here. 🙂

Well, they're kind of solved, at this point. 1) I wanted to control where the .cfg and .log files were created (solved by changing directory into the desired location before running executable), and 2) I wanted to enable FULLSCREEN to hide the mouse pointer (solved by using runtime command-line option (-f)ullscreen).

I still don't know how the build options are to be enabled, but I guess I don't need them any longer (and they might not have done what I wanted in the first place, at least not the first one.)
